[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
categories = ["graphics", "data-structures", "algorithms"]
description = "computational geometry library"
edition = "2021"
keywords = ["compgeom", "geometry"]
license = "MIT OR Apache-2.0"
name = "memegeom"
repository = "https://github.com/Edgeworth/memegeom"
version = "0.1.0"

[dependencies]
approx = "0.5.1"
auto_ops = "0.3.0"
derive_more = "0.99.17"
earcutr = "0.2.0"
itertools = "0.10.3"
nalgebra = "0.30.1"
ordered-float = "2.10.0"
rand = {version = "0.8.5", features = ["small_rng"]}
rust-dense-bitset = "0.1.1"
serde = {version = "1.0.136", features = ["derive"]}
smallvec = "1.8.0"

# Build dependencies with optimisations - debug builds will run faster
# but dependencies don't change often.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
