[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
categories = ["graphics", "data-structures", "algorithms"]
description = "computational geometry library"
edition = "2021"
keywords = ["compgeom", "geometry"]
license = "MIT OR Apache-2.0"
name = "memegeom"
repository = "https://github.com/Edgeworth/memegeom"
version = "0.1.0"

[dependencies]
ahash = "0.8.11"
approx = "0.5.1"
auto_ops = "0.3.0"
derive_more = "0.99.17"
earcutr = "0.4.3"
itertools = "0.12.1"
nalgebra = "0.32.4"
ordered-float = "4.2.0"
rand = {version = "0.8.5", features = ["small_rng"]}
rust-dense-bitset = "0.1.1"
serde = {version = "1.0.197", features = ["derive"]}
smallvec = "1.13.2"

[dev-dependencies]
pretty_assertions = "1.4.0"
