[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
categories = ["graphics", "data-structures", "algorithms"]
description = "computational geometry library"
edition = "2021"
keywords = ["compgeom", "geometry"]
license = "MIT OR Apache-2.0"
name = "memegeom"
repository = "https://github.com/Edgeworth/memegeom"
version = "0.1.0"

[dependencies]
approx = "0.5.1"
auto_ops = "0.3.0"
derive_more = "0.99.17"
earcutr = "0.2.0"
itertools = "0.10.3"
nalgebra = "0.31.0"
ordered-float = "3.0.0"
rand = { version = "0.8.5", features = ["small_rng"] }
rust-dense-bitset = "0.1.1"
serde = { version = "1.0.137", features = ["derive"] }
smallvec = "1.8.0"
